version: '3.4'

# For development (automatically picked-up unless another -f override is specified)

services:

  # extending
  solomon:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
    environment:
      - DEBUG=${DEBUG}

  # included for convenience
  # exits when complete (which causes prod deploy failure)
  migrations:
    image: 383314943195.dkr.ecr.us-east-1.amazonaws.com/solomon:latest
    command: "python3 manage.py migrate"
    secrets:
      - db-username
      - db-password
      - db-host
      - db-port
      - db-name
      - django-secret-key
    build:
      context: ./backend
    depends_on:
      mysql:
        condition: service_healthy
  
  # extending
  solomon-ui:
    build:
      context: ./ui

  mysql:
    image: mysql:5.7
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      timeout: 3s
      retries: 10
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/db-name
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-rootpassword
      MYSQL_USER_FILE: /run/secrets/db-username
      MYSQL_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-name
      - db-rootpassword
      - db-username
      - db-password

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql

secrets:
  db-name:
    file: ./local-secrets/db-name.txt
  db-username:
    file: ./local-secrets/db-username.txt
  db-password:
    file: ./local-secrets/db-password.txt
  db-host:
    file: ./local-secrets/db-host.txt
  db-port:
    file: ./local-secrets/db-port.txt
  db-rootpassword:
    file: ./local-secrets/db-rootpassword.txt

  django-secret-key:
    file: ./local-secrets/django-secret-key.txt
