version: '3.4'

# For development (automatically picked-up unless another -f override is specified)

services:

  # extending
  solomon:
    build:
      context: ./backend
    ports:
      - 3000:3000
    environment:
      - CORS_ORIGIN_WHITELIST=https://solomon.money
    depends_on:
      migrations:
        condition: service_started
    healthcheck:
      interval: 5s

  # included for convenience
  # exits when complete (which causes prod deploy failure)
  migrations:
    image: 383314943195.dkr.ecr.us-east-1.amazonaws.com/solomon:latest
    command: "python3 manage.py migrate"
    networks:
      - solomon
    secrets:
      - db-migration-username
      - db-migration-password
      - db-host
      - db-port
      - db-name
      - django-secret-key
    build:
      context: ./backend
    depends_on:
      mysql:
        condition: service_healthy
  
  # extending
  solomon-ui:
    healthcheck:
      interval: 5s
      retries: 12

  # prod mysql (switch to managed service when costs are warranted)
  mysql:
    image: mysql:5.7
    networks:
      - solomon
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    healthcheck:
      test: mysqladmin ping -uroot -p`cat /run/secrets/db-rootpassword`
      interval: 15s
      timeout: 3s
      retries: 3
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-rootpassword
    secrets:
      - db-rootpassword

  myadmin:
    networks:
      - solomon
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql

secrets:
  db-name:
    file: ./secrets/db-name

  db-username:
    file: ./secrets/db-username
  db-password:
    file: ./secrets/db-password
  
  db-migration-username:
    file: ./secrets/db-migration-username
  db-migration-password:
    file: ./secrets/db-migration-password

  db-host:
    file: ./secrets/db-host
  db-port:
    file: ./secrets/db-port

  db-rootpassword:
    file: ./secrets/db-rootpassword

  django-secret-key:
    file: ./secrets/django-secret-key
  
  configcat-key:
    file: ./secrets/configcat-key
