version: '3.4'

# For development (automatically picked-up unless another -f override is specified)

services:

  # extending
  solomon:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
    environment:
      - DEBUG=${DEBUG}
    depends_on:
      migrations:
        condition: service_started

  # included for convenience
  # exits when complete (which causes prod deploy failure)
  migrations:
    image: 383314943195.dkr.ecr.us-east-1.amazonaws.com/solomon:latest
    command: "python3 manage.py migrate"
    networks:
      - solomon
    secrets:
      - db-migration-username
      - db-migration-password
      - db-host
      - db-port
      - db-name
      - django-secret-key
    build:
      context: ./backend
    depends_on:
      mysql:
        condition: service_healthy
  
  # extending
  solomon-ui:
    build:
      context: ./ui

  mysql:
    image: mysql:5.7
    networks:
      - solomon
    command: --init-file /tmp/seed-database.sql
    volumes:
      - .:/tmp
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      timeout: 3s
      retries: 10
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-rootpassword
    secrets:
      - db-rootpassword

  myadmin:
    networks:
      - solomon
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_HOST: ${DB_HOST:-mysql}

secrets:
  db-name:
    file: ./local-secrets/db-name.txt

  db-username:
    file: ./local-secrets/db-username.txt
  db-password:
    file: ./local-secrets/db-password.txt
  
  db-migration-username:
    file: ./local-secrets/db-migration-username.txt
  db-migration-password:
    file: ./local-secrets/db-migration-password.txt

  db-host:
    file: ./local-secrets/db-host.txt
  db-port:
    file: ./local-secrets/db-port.txt

  db-rootpassword:
    file: ./local-secrets/db-rootpassword.txt

  django-secret-key:
    file: ./local-secrets/django-secret-key.txt
