version: '3.4'

# For development (automatically picked-up unless another -f override is specified)

services:

  # extending
  solomon:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000

  # extending
  migrations:
    build:
      context: ./backend
    depends_on:
      mysql:
        condition: service_healthy
  
  # extending
  solomon-ui:
    build:
      context: ./ui

  mysql:
    image: mysql:5.7
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      timeout: 3s
      retries: 10
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: data
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
