# Generated by Django 3.1.1 on 2021-01-18 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20201111_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userid', models.CharField(editable=False, max_length=128)),
                ('date', models.DateField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('set_aside', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
            ],
        ),
    ]
