# Generated by Django 3.1.1 on 2021-01-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_parameters'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parameters',
            constraint=models.UniqueConstraint(fields=('userid', 'date'), name='one_parameter_set_per_day'),
        ),
    ]
