# Generated by Django 3.1.1 on 2021-01-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_auto_20210119_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='date',
            field=models.DateField(editable=False),
        ),
    ]
