name: Backend Unit Tests

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Backend unit tests
        run: docker-compose run --rm --no-deps solomon python manage.py test
