on:
   push:
     branches: [ main ]
   workflow_dispatch:


name: Deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Add solomon context
      run: |
        curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
        docker context create ecs --from-env solomon

    - name: Writing secrets
      run: |
        mkdir -p secrets || true
        echo "$DB_NAME" > ./secrets/db-name
        echo "$DB_USERNAME" > ./secrets/db-username
        echo "$DB_PASSWORD" > ./secrets/db-password
        echo "$DB_MIGRATION_USERNAME" > ./secrets/db-migration-username
        echo "$DB_MIGRATION_PASSWORD" > ./secrets/db-migration-password
        echo "$DB_ROOTPASSWORD" > ./secrets/db-rootpassword
        echo "$DB_HOST" > ./secrets/db-host
        echo "$DB_PORT" > ./secrets/db-port
        echo "$DJANGO_SECRET_KEY" > ./secrets/django-secret-key
      env:
        DB_NAME: ${{secrets.DB_NAME}}
        DB_USERNAME: ${{secrets.DB_USERNAME}}
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        DB_MIGRATION_USERNAME: ${{secrets.DB_MIGRATION_USERNAME}}
        DB_MIGRATION_PASSWORD: ${{secrets.DB_MIGRATION_PASSWORD}}
        DB_ROOTPASSWORD: ${{secrets.DB_ROOTPASSWORD}}
        DB_HOST: ${{secrets.DB_HOST}}
        DB_PORT: ${{secrets.DB_PORT}}
        DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}

    - name: Docker Layer Caching
      uses: satackey/action-docker-layer-caching@v0.0.11

    - name: Run update script
      run: |
        ./update.sh
