on:
#    push:
#      branches: [ main ]
   workflow_dispatch:


name: Deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Docker Layer Caching
      uses: satackey/action-docker-layer-caching@v0.0.11

    - name: Build images
      run: |
         TAG=`git rev-parse HEAD` docker-compose build solomon-ui solomon
         aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 383314943195.dkr.ecr.us-east-1.amazonaws.com
         TAG=`git rev-parse HEAD` docker-compose push solomon-ui solomon

    - name: Add SSH agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{secrets.SSH_KEY_GIT}}

    - name: Connect to droplet and update
      run: |
         echo "$DROPLET_SSH_KEY" > droplet_key
         ssh -A -i droplet_key root@167.71.186.2 "cd solomon && git fetch && git checkout main && git pull && ./update-droplet.sh"
      env:
         SSH_KEY_GIT: ${{secrets.SSH_KEY_GIT}}
         DROPLET_SSH_KEY: ${{secrets.DROPLET_SSH_KEY}}
