name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Backend unit tests
        run: docker-compose run --rm --no-deps solomon python manage.py test
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
          check-latest: yes

      - name: Frontend unit tests
        run: |
          cd ui
          yarn --frozen-lockfile
          CI=true yarn test -u --ci --coverage --reporters=default --reporters=jest-junit
