on:
   push:
     branches: [ main ]
   workflow_dispatch:


name: Publish Storybook

jobs:
  deploy:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 15.x
        check-latest: yes
    
    - name: Yarn Install
      uses: bahmutov/npm-install@v1.6.0
      with:
        working-directory: ui
        useLockFile: yes

    - name: Deploy Storybook
      run: cd ui; yarn deploy-storybook
